version: '3.8'

services:
  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: spring_base
      MYSQL_USER: kell
      MYSQL_PASSWORD: kell0502
    networks:
      - dsf_network

  # Spring Boot Application
  spring-app:
    image: spring:version1
    container_name: spring-app-container
    ports:
      - "8089:8088"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/spring_base
      SPRING_DATASOURCE_USERNAME: kell
      SPRING_DATASOURCE_PASSWORD: kell0502
      SPRING_PROFILES_ACTIVE: docker
    restart: always
    networks:
      - dsf_network

networks:
  dsf_network:
    driver: bridge