version: '3.8'

services:
  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: store_db
      MYSQL_USER: root
      MYSQL_PASSWORD: kell0502
    networks:
      - dsf_network

  # Spring Boot Application
  spring-app:
    image: your-spring-boot-image:latest
    container_name: spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/store_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kell0502
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - dsf_network

networks:
  dsf_network:
    driver: bridge